// Route: /
import styles from './page.module.css';
import { SignIn } from '../components/auth/SignIn';
import { SignUp } from '../components/auth/SignUp';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { routes } from './config/routes';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'CryptoDashboard',
  description: 'Generated by lmd',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function Home() {
  const cookieStore = cookies();
  const sessionCookie = cookieStore.get('session');

  if (sessionCookie) {
    redirect(routes.dashboard);
  }

  return (
    <main className={styles.main}>
      <div className={styles.authMenu}>
        <SignIn />
        <SignUp />
      </div>
    </main>
  );
}
