[build]
builder = "DOCKERFILE"
dockerfilePath = ".railway/Dockerfile"

[deploy]
startCommand = "pnpm turbo run start --filter back"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[deploy.env]
NODE_ENV = "production"

[nixpacks]
node_version = "20" 