[build]
builder = "DOCKERFILE"
dockerfilePath = ".railway/Dockerfile"

[deploy]
startCommand = "sh -c 'cd back && PORT=8080 node dist/index.js'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[deploy.env]
PORT = "8080"

[nixpacks]
node_version = "20" 