[build]
builder = "DOCKERFILE"
dockerfilePath = ".railway/Dockerfile"

[deploy]
startCommand = "pnpm turbo run start --filter back"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
node_version = "20" 