[build]
builder = "DOCKERFILE"
dockerfilePath = ".railway/Dockerfile"

[deploy]
startCommand = "sh -c 'cd back && node dist/index.js'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[nixpacks]
node_version = "20" 