export const metadata: Metadata = {
  title: 'Addresses - CryptoDashboard',
  description: 'Generated by lmd',
};

import type { Metadata } from 'next';
export default function AddressesLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
