name: CI - Tests & build

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      CONNECTION_STRING_TEST: ${{ secrets.CONNECTION_STRING_TEST }}
      NODE_ENV: 'test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.0'
          cache: 'pnpm'
      - name: Install pnpm
        run: pnpm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build shared
        run: pnpm run build-shared
      - name: Build front-end
        run: pnpm run build-front
        env:
          NEXT_PUBLIC_API_URL: 'http://localhost:4000'
      - name: Build back-end
        run: pnpm run build-back
      - name: Debug Environment Variables
        run: |
          echo "CONNECTION_STRING_TEST=${CONNECTION_STRING_TEST}"
          echo "NODE_ENV=${NODE_ENV}"
          echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}"
        env:
          CONNECTION_STRING_TEST: ${{ secrets.CONNECTION_STRING_TEST }}
          NODE_ENV: 'test'
      - name: Run tests
        run: pnpm test
        env:
          CONNECTION_STRING_TEST: ${{ secrets.CONNECTION_STRING_TEST }}
          NEXT_PUBLIC_API_URL: 'http://localhost:4000' # For frontend tests
